### ISSUE TITLE
Course page

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#107]
As a user, I want to be able to view a page which summarizes course information and shows reviews and questions for that course, and gives me the option to submit reviews and questions.

Acceptance tests:
- Course page with header showing course name and space for future aggregated rating/question information
- 'Tabs' for Info, Questions and Reviews
- For Question and Review tabs, a 'feed' or list of items, which can be clicked to go to the single-page version of the question or review
- For info tab, a space for the most important course information; i.e. scraped Handbook description etc

**Comment by DarkPurple141** [comment]
Prepping this for next sprint. It's partly done in feed but will need a rework. Important page to get right.

**Comment by NunoDasNeves** [comment]
![courseinfo.png](https://images.zenhubusercontent.com/5b6a9a759402e7613330c4d1/7b7ac95d-8ad1-4c3d-9982-962974c14183)
![coursequestions.png](https://images.zenhubusercontent.com/5b6a9a759402e7613330c4d1/83027ff7-bb02-4198-a99e-e0d80a715aa9)

**Comment by DarkPurple141** [comment]
Partially dealt with in #135
