### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#121]
As a visitor to the site, if something goes wrong I want to be presented with a clear message that indicates what went wrong and what I should do.

As someone trying to breach or fuzz the site, I should not get server stack traces or other non-essential information.

Acceptance tests:
- It doesn't have to be very specific in most cases - e.g. 'Unknown error - refresh & try again' is okay for now.
- However, there should be mechanisms for delivering specific error messages for things that could go wrong at all levels of the system (frontend, backend, database) - e.g. logging in should obviously show the user a 'wrong username or password' message if they typed their details wrong instead of just telling them to refresh and try again
- Consistent methods for error handling in frontend and backend
- Making sure stack traces etc don't get returned; i.e. server's default error response body is something benign

**Comment by DarkPurple141** [comment]
I think this is quite close but moving it forward in any case.

**Comment by DarkPurple141** [comment]
Resolved in 2008. #127
