### ISSUE TITLE
Frontend: Review/Course Module

### ISSUE THREAD

**Issue by DarkPurple141** [SmartCourse/app#128]
* Should update frontend state and make appropriate backend query
* Frontend state updates will require interactions with a new Vuex store module

**Comment by NunoDasNeves** [comment]
![Screenshot from 2018-09-06 15-54-36.png](https://images.zenhubusercontent.com/5b6a9a759402e7613330c4d1/9bfeae4e-caf2-437f-9f57-a460c2f03fbf)

**Comment by NunoDasNeves** [comment]
![coursequestions.png](https://images.zenhubusercontent.com/5b6a9a759402e7613330c4d1/5ed6307a-a5ee-4c0f-ad40-66e2e6c2e425)
