### ISSUE TITLE
Project Doc For Submission

### ISSUE THREAD

**Issue by PapaPwn** [SmartCourse/app#131]
Just a place to add the additional images so markdown works nicely and for you guys to check the doc is all g.

**Comment by PapaPwn** [comment]
![user story](https://user-images.githubusercontent.com/26681270/45141674-e31b7280-b1f9-11e8-984f-70731a829283.png)
![task](https://user-images.githubusercontent.com/26681270/45141677-e7479000-b1f9-11e8-86d8-77f489481a01.png)
![all stories](https://user-images.githubusercontent.com/26681270/45141680-ea428080-b1f9-11e8-9b9f-966f5f794de7.png)
![all tasks](https://user-images.githubusercontent.com/26681270/45141683-ee6e9e00-b1f9-11e8-8e7d-cdfca4349535.png)
![start_of_sprint](https://user-images.githubusercontent.com/26681270/45141691-f29abb80-b1f9-11e8-8e80-2b271d1eae8c.png)

**Comment by DarkPurple141** [comment]
Resolved by #132 Well done @PapaPwn 🥇 .
