### ISSUE TITLE
Course ratings and aggregation

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#150]
Reviewers should be able to add ratings for courses they review.
These ratings should be stored in both separate and aggregated form (review table and course table) in the backend.
The course page header should show aggregated ratings (a mean is fine for now), and the number of reviewers who voted on each rating.

Each rating should be optional (?) In future we may want to present a selection of questions.
Ratings should be 1-3, and sort of 'disguised' as qualitative.

e.g.

Was the course content difficult to learn for you?
It was relatively easy, Medium difficulty, Very challenging

What was the workload like for you?
Few hours per week, Medium workload, Highly time-consuming

Do you think the content was taught effectively?
It could be improved, Reasonably well, Very well

Was this course intellectually and/or creatively satisfying for you?
Not very, Somewhat, Very much so

**Comment by DarkPurple141** [comment]
Moved to Sprint 7.
