### ISSUE TITLE
Improve scraping and html stripping for course data

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#169]
The main actual BUG is on the COMP4920 course page; you can see that <ul> and <li> tags have been stripped. But just fixing this isn't the point of this issue.

Currently, scraped data is sanitized and stripped in `scripts/scraper.py`
Running the scraper takes ages (~40 mins) and filtering the right html tags etc is tricky

Better solution would be:
- Remove most sanitization from python scraper. Just get all the raw data
- Do html sanitization (remove all tags except <i>, <b>, <p>, <ul> etc...) offline. E.g., in the javascript that loads the data into the db, or a separate python script

Then we can process the text offline and fix bugs in processing there without wasting mucho time.

**Comment by DarkPurple141** [comment]
Resolved by @PapaPwn
