### ISSUE TITLE
Migrate to permanent SQLite DB

### ISSUE THREAD

**Issue by PapaPwn** [SmartCourse/app#176]
_The original plan was to setup a MySQL server, but due to pricing going to just have a SQLite file stored on each server and only worry about further scaling IF needed._

We need to have a more permanent hosted database, which is separated from testing data.
Criteria:
- [x] Setup an initial SQLite database file.
- [x] Refactor our code so that production and staging use the SQLite database file.
- [x] Setup some automated backing up of the database so we don't suddenly lose everything.

**Comment by DarkPurple141** [comment]
Resolved by #187.
