### ISSUE TITLE
Sign up flow consistency improvement

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#204]
Remove inconsistencies in signup flow in case of backend entry not being created.

Signup/login is like:
- ask firebase for token
- we get le token, and send it to backendski
- if POSTed to /user endpoint, and user doesn't exist, create user
- if any request at all occurs with a token for a NON existent user in backend, should redirect to account creation step 2, or do this transparently & sign user in.

**Comment by DarkPurple141** [comment]
BTW, partly done some things in this in my PR. In fact u know what I need to just merge my PR.
