### ISSUE TITLE
Backend error handling framework

### ISSUE THREAD

**Issue by NunoDasNeves** [SmartCourse/app#309]
The old error ticket #121 wasn't really resolved properly.
A flexible, simple way of handling and propagating errors in the backend needs to be built and added to all routes.

Currently:
- All (handled) errors return status 400 - this is fine as a default
- Often SQL error text is put into the body of the request etc...
- Missing resources on valid routes (e.g. nonexistent questions) return status 200, which is just wrong

Ideally:
- It should be simple to handle and propagate errors at several levels (controller, model), specifying a status code and message
- Detailed error information (e.g. SQL errors, stack traces) should be logged, not sent in the response
- Nonexistent resources should return 404 - e.g. querying for a missing question should detect that the SQL query returned nothing and send a 404 response

**Comment by DarkPurple141** [comment]
Resolved by #314
