### ISSUE TITLE
Boilerplate Code

### ISSUE THREAD

**Issue by DarkPurple141** [SmartCourse/app#39]
Project needs boilerplate code for:

* Frontend, (VueJS)
* Backend, (ExpressJS)

**Comment by PapaPwn** [comment]
Isn't Vue for the frontend and Express for the backend?

**Comment by DarkPurple141** [comment]
Oh yep. Good catch. The actual issues didn't make this mistake. @PapaPwn

**Comment by DarkPurple141** [comment]
@PapaPwn Feel free to make change directly if it's this overt next time XD

**Comment by DarkPurple141** [comment]
Resolved by #85, #69
