### ISSUE TITLE
Answer Questions

### ISSUE THREAD

**Issue by PapaPwn** [SmartCourse/app#47]
As a student or lecturer, I want to be able to answer questions posted about a course to help the learning community.

Acceptance tests:
- There should be a form on the single question page for entering an answer to a question, with a button that says 'Answer' or similar
- The user should be able to enter a question Body (no title or anything else)
- After answering, the page should be reloaded and the newly submitted answer should be shown in the list of answers

**Comment by DarkPurple141** [comment]
I feel like this is kinda done. Is the required functionality all there? Seems like it.

**Comment by NunoDasNeves** [comment]
Yes, is done

**Comment by NunoDasNeves** [comment]
Product owner approved

**Comment by DarkPurple141** [comment]
Mind I still don't love that we reload all the answers. But yeah. Something for another day.
