### ISSUE TITLE
Upvote/Rate a Review

### ISSUE THREAD

**Issue by Aruzal** [SmartCourse/app#73]
As a student I want to up-vote a review so that I can provide feedback that it was useful and relevant.

Acceptance criteria:
- Similar to Question upvoting, a review should have an update or like button
- A review should show the number of upvote
- Only logged in users can upvote: if not logged in, pressing the button goes to login screen (or just an alert telling them they must login)

**Comment by DarkPurple141** [comment]
Resolved by #192, #196.
